import json
import os

def run_completion():
    if not os.path.exists("repo_map.json"):
        print("❌ Error: Run analysis phase first.")
        return

    with open("repo_map.json", "r") as f:
        repo_map = json.load(f)

    missing = repo_map.get("missing_elements", [])
    
    plan = "# Completion Plan & Execution Log\n\n"
    plan += "## 🛠 Auto-Generated Patches\n"
    
    os.makedirs("patches", exist_ok=True)
    
    for item in missing:
        if item == "README.md":
            with open("README.md", "w") as f:
                f.write("# Project Name\n\nAuto-generated by Repo Operator Protocol.")
            plan += "- ✅ Created `README.md`\n"
        elif item == ".env.example":
            with open(".env.example", "w") as f:
                f.write("PORT=3000\nDATABASE_URL=mongodb://localhost:27017/mydb\n")
            plan += "- ✅ Created `.env.example`\n"
            
    # Upgrade hooks
    hooks = {
        "protocol_version": "2.0",
        "last_run": "today",
        "hooks": [
            {"phase": "analysis", "auto_run": True},
            {"phase": "validation", "auto_run": True}
        ]
    }
    with open("upgrade_hooks.json", "w") as f:
        json.dump(hooks, f, indent=2)
    plan += "- ✅ Embedded `upgrade_hooks.json`\n"

    with open("completion_plan.md", "w") as f:
        f.write(plan)
    
    print("✅ Completion phase complete.")

if __name__ == "__main__":
    run_completion()
